#!/bin/sh
# Start/stop the cntlm proxy.
#
### BEGIN INIT INFO
# Provides:          cntlm
# Required-Start:    $syslog $time
# Required-Stop:     $syslog $time
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Authenticating HTTP accelerator for NTLM secured proxies
# Description:       Cntlm is meant to be given your proxy address and becomming
#                    the primary proxy then, listening on a selected local port. 
#                    You point all your proxy-aware programs to it and don't ever
#                    have to deal with proxy authentication again.
#
# DAEMON             Location of the binary
# PIDFILE            Make sure that you or, if used, -U uid can create/write it
# TIMEOUT            How long to wait before forcing cntlm to stop with a second 
#                    signal when active connections are still not finished
# RUNAS              Name or number of the non-privileged account to run as
#
### END INIT INFO

DAEMON=/usr/local/bin/cntlm
PIDFILE=/var/run/cntlm.pid
TIMEOUT=5
RUNAS=nobody

NAME=cntlm
DESC="CNTLM Authentication Proxy"
OPTARGS="-U $RUNAS -P $PIDFILE"

test -f $DAEMON || exit 0

case "$1" in
	start)	echo "Starting $DESC"
		start-stop-daemon --start --pidfile $PIDFILE --name $NAME --startas $DAEMON -- $OPTARGS
		;;
	stop)	echo "Stopping $DESC"
		start-stop-daemon --stop --retry -HUP/$TIMEOUT/-HUP/2/-KILL/forever --pidfile $PIDFILE --name $NAME
		;;
	restart) echo "Restarting $DESC"
		start-stop-daemon --stop --retry -HUP/$TIMEOUT/-HUP/2/-KILL/forever --pidfile $PIDFILE --name $NAME
		start-stop-daemon --start --pidfile $PIDFILE --name $NAME --startas $DAEMON -- $OPTARGS
		;;
	*)	echo "Usage: $0 {start|stop|restart}" >&2
		exit 2
		;;
esac

exit 0
