#!/bin/sh
#
# Postinst script for cntlm
#

set -e

NAME=cntlm
HOME=/var/run/cntlm

# Create cntlm user and its homedir
if ! getent passwd $NAME >/dev/null; then
	adduser --system --home $HOME --shell /bin/sh --disabled-password $NAME
fi

if ! [ -d $HOME ]; then
	mkdir -p $HOME
	chmod 755 $HOME
	chown -h -R $NAME $HOME
fi

#DEBHELPER#

# Automatically added by dh_installinit
if [ -x "/etc/init.d/cntlm" ]; then
	update-rc.d cntlm defaults >/dev/null
	if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
		invoke-rc.d cntlm start || exit $?
	else
		/etc/init.d/cntlm start || exit $?
	fi
fi
# End automatically added section
