#!/bin/sh
#
# Postinst script for cntlm
#

set -e

NAME=cntlm
HOME=/var/run/cntlm

# Create cntlm user and its homedir
if ! getent passwd $NAME >/dev/null; then
	adduser --system --ingroup nogroup --home $HOME --shell /bin/sh --disabled-password $NAME
fi

if ! [ -d $HOME ]; then
	mkdir -p $HOME
fi

chmod 600 /etc/$NAME.conf
chmod 700 $HOME
chown -h -R $NAME:nogroup $HOME

if [ -x /etc/init.d/$NAME ]; then
	update-rc.d $NAME defaults 99 15 >/dev/null

	if [ -x /usr/sbin/invoke-rc.d ]; then
		invoke-rc.d --quiet $NAME start || true
	else
		/etc/init.d/$NAME start || true
	fi
fi

exit 0
