#!/bin/sh

NAME=cntlm

# Stops daemon if it is running under our control
if [ -x /etc/init.d/$NAME ]; then
	if [ -x /usr/sbin/invoke-rc.d ]; then
		invoke-rc.d --quiet $NAME stop
	else
		/etc/init.d/$NAME stop
	fi
fi

# Automatically added by dh_installinit
if [ -x "/etc/init.d/cntlm" ]; then
	if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
		invoke-rc.d cntlm stop || exit $?
	else
		/etc/init.d/cntlm stop || exit $?
	fi
fi
# End automatically added section
